name: Automation test

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - test_authorization
          - test_bulletin
          - test_form_fill
          - test_just_in
          - test_live
          - test_newsletters
          - test_programmes
          - test_search
          - test_weather
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: test_authorization
        if: "github.event.inputs.deployment_target == 'test_authorization'"
        run: pytest tests/test_authorization.py::test_authorization
      - name: test_bulletin
        if: "github.event.inputs.deployment_target == 'test_bulletin'"
        run: pytest tests/test_bulletin.py::test_bulletin
      - name: test_form_fill
        if: "github.event.inputs.deployment_target == 'test_form_fill'"
        run: pytest tests/test_form_fill.py::test_form_fill
      - name: test_just_in
        if: "github.event.inputs.deployment_target == 'test_just_in'"
        run: pytest tests/test_just_in.py::test_just_in
      - name: test_live
        if: "github.event.inputs.deployment_target == 'test_live'"
        run: pytest tests/test_live.py::test_live
      - name: test_newsletters
        if: "github.event.inputs.deployment_target == 'test_newsletters'"
        run: pytest tests/test_newsletters.py::test_newsletters
      - name: test_programmes
        if: "github.event.inputs.deployment_target == 'test_programmes'"
        run: pytest tests/test_programmes.py::test_programmes
      - name: test_search
        if: "github.event.inputs.deployment_target == 'test_search'"
        run: pytest tests/test_search.py::test_search
      - name: test_weather
        if: "github.event.inputs.deployment_target == 'test_weather'"
        run: pytest tests/test_weather.py::test_weather